# Generated by Django 3.2.4 on 2023-02-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20230220_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stateGovtFunddb',
        ),
    ]
