# Generated by Django 3.2.4 on 2023-02-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_delete_stategovtfunddb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AngelInvestorsDB',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='DemodayDB',
        ),
        migrations.DeleteModel(
            name='GlobalMarketConnectDB',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='StateGovernmentFundingDB',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='VentureCapitalistDB',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
