# Generated by Django 3.2.4 on 2023-02-20 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20230220_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryforBlogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforEvents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforExperience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforGallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforQualification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforStartups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryforTeams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_val', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
