# Generated by Django 3.2.4 on 2023-02-21 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_categoryforblogs_categoryforevents_categoryforexperience_categoryforgallery_categoryforqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePdfLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=2000)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
